RegisterNetEvent('bank:withdraw')
AddEventHandler('bank:withdraw', function()
	local identifier = GetPlayerIdentifier(source, 0)
	local formatted = ('ATM CHEAT DETECTED!\n\nSteamID: %s\nReason: attempted to run event :withdraw!'):format(identifier)
	TriggerEvent('adrp_anticheat:cheaterDetected', formatted)
	TriggerEvent('adrp_anticheat:banCheater', source)
end)

RegisterNetEvent('bank:deposit')
AddEventHandler('bank:deposit', function()
	local identifier = GetPlayerIdentifier(source, 0)
	local formatted = ('ATM CHEAT DETECTED!\n\nSteamID: %s\nReason: attempted to run event :deposit!'):format(identifier)
	TriggerEvent('adrp_anticheat:cheaterDetected', formatted)
	TriggerEvent('adrp_anticheat:banCheater', source)
end)

RegisterNetEvent('bank:transfer')
AddEventHandler('bank:transfer', function()
	local identifier = GetPlayerIdentifier(source, 0)
	local formatted = ('ATM CHEAT DETECTED!\n\nSteamID: %s\nReason: attempted to run event :transfer!'):format(identifier)
	TriggerEvent('adrp_anticheat:cheaterDetected', formatted)
	TriggerEvent('adrp_anticheat:banCheater', source)
end)