Config.AuthorizedHelicopters = {
	['police'] = {
		{model = 'mh65c', label = 'MH 65 C', livery = 0, price = 100000}
	},

	['sheriff'] = {
		{model = 'mh65c', label = 'MH 65 C', livery = 0, price = 100000}
	},

	['state'] = {
		{model = 'mh65c', label = 'MH 65 C', livery = 0, price = 100000}
	},

	['securoserv'] = {
		{model = 'mh65c', label = 'MH 65 C', livery = 0, price = 100000}
	},

	['usmarshal'] = {
		{model = 'frogger2', label = 'FIB Frogger', livery = 0, price = 200000}
	},

	['dod'] = {
		{model = 'mh65c2', label = 'USCG MH-65C "Dolphin"', livery = 0, price = 100000},
		{model = 'jayhawk', label = 'USCG "Jayhawk"', livery = 0, price = 100000},
		{model = 'cl415', label = 'CL-415 Superscooper', livery = 0, price = 100000},
		{model = 'f14', label = 'F-14 Tomcat', livery = 0, price = 100000},
		{model = 'f15', label = 'F-15 Eagle', livery = 0, price = 100000},
		{model = 'f16', label = 'F-16 Fighting Falcon', livery = 0, price = 100000},
		{model = 'ea18', label = 'F-18 Super Hornet', livery = 0, price = 100000},
		{model = 'f22', label = 'F-22 Raptor', livery = 0, price = 100000},
		{model = 'f117', label = 'F-117 Nighthawk', livery = 0, price = 100000},
		{model = 'vtol', label = 'F-35 Lighting II', livery = 0, price = 100000},
		{model = 'wp3', label = 'WP-3D Orion', livery = 0, price = 100000},
		{model = 'blackbird', label = 'SR-71 Blackbird', livery = 0, price = 100000},
		{model = 'titan', label = 'Titan', livery = 0, price = 100000},
		{model = 'e2d', label = 'E-2D Hawkeye', livery = 0, price = 100000},
		{model = 'kc10', label = 'KC-10 Extender', livery = 0, price = 100000},
		{model = 'mq9', label = 'MQ-9 Reaper', livery = 0, price = 100000},
		{model = 'mh60a', label = 'MH-60 A', livery = 0, price = 100000},
		{model = 'mh60b', label = 'MH-60 B', livery = 0, price = 100000},
		{model = 'mh60c', label = 'MH-60 C', livery = 0, price = 100000},
		{model = 'mh60d', label = 'MH-60 D', livery = 0, price = 100000},
		{model = 'mh60e', label = 'MH-60 E', livery = 0, price = 100000},
		{model = 'mh60f', label = 'MH-60 F', livery = 0, price = 100000},
		{model = 'mh60g', label = 'MH-60 G', livery = 0, price = 100000},
		{model = 'mh60h', label = 'MH-60 H', livery = 0, price = 100000},
		{model = 'mh60i', label = 'MH-60 I', livery = 0, price = 100000},
		{model = 'oh6a', label = 'OH-6 Cayuse', livery = 0, price = 100000},
		{model = 'uh1y', label = 'UH-1 Venom', livery = 0, price = 100000},
		{model = 'viper2', label = 'AH-1Z Viper', livery = 0, price = 100000},
		{model = 'ahx', label = 'MH-60 Ghosthawk', livery = 0, price = 100000},
		{model = 'hunter', label = 'Hunter Attack', livery = 0, price = 100000},
		{model = 'cargobob', label = 'Cargobob', livery = 0, price = 100000},
	},
	
	['fib'] = {
		{model = 'frogger2', label = 'FIB Frogger', livery = 0, price = 200000}
	}
}

Config.AuthorizedBoats = {
	['dod'] = {
		{model = 'defender', label = 'Patrol Boat', livery = 0, price = 10000},
		{model = 'cb90', label = 'Military Patrol Boat', livery = 0, price = 10000}
	}
}

Config.PoliceAuthorizedVehicles = {
	recruit = {
		{model = 'scorcher', label = 'Bicycle', price = 1}
	},

	officer = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	senofficer = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	snrofficer = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	sergeant = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
	},

	commander = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
	},

	lieutenant = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
	},

	captain = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	asstchief = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'silv', label = 'Silverado', price = 55000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	chief = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'capriceleo', label = 'Caprice', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	depcomm = {
		{model = 'polcvpi', label = 'CVPI', price = 200}
	},

	comm = {
		{model = 'polcvpi', label = 'CVPI', price = 200}
	}
}

Config.SheriffAuthorizedVehicles = {
	cadet = {
		{model = 'scorcher', label = 'Bicycle', price = 1},
		{model = 'polimpala', label = 'impala', price = 5000},
	},

	deputy = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	corporal = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	sgt = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	cmdr = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	chiefdep = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	under = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	asst = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	sheriff = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'sraptor2', label = 'Sheriff Raptor', price = 50000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'sheriffbike', label = 'Harley Davidson', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	}
}

Config.StateAuthorizedVehicles = {
	cadet = {
		{model = 'scorcher', label = 'Bicycle', price = 1}
	},

	trooper = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
	},

	tfc = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	mastertrooper = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	corporal = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	sgt = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	firstsgt = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	lieutenant = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	captain = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	major = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	ltcol = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	colonel = {
		{model = 'polcvpi', label = 'CVPI', price = 200},
		{model = 'polimpala', label = 'impala', price = 5000},
		{model = 'stopcharger2', label = 'DOA ONLY', price = 65000},
		{model = 'polfpiu', label = 'FPIU', price = 15000},
		{model = 'polcharger', label = 'Charger', price = 30000},
		{model = 'poltahoe', label = 'Tahoe', price = 20000},
		{model = 'poltahoe2', label = 'Tahoe 2013', price = 15000},
		{model = 'poltaurus', label = 'Taurus', price = 5000},
		{model = 'interceptor', label = 'Ghost Charger', price = 40000},
		{model = 'polbike', label = 'BMW Bike', price = 45000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'riot', label = 'Swat-1', price = 50000},
		{model = 'pdbrick', label = 'Emergency Responce', price = 25000},
		{model = 'policet', label = 'Transport Van', price = 15000},
		{model = 'scorcher', label = 'Bicycle', price = 200},
		-- {model = '18silverado', label = '18 Silverado', price = 40000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'bcsoriot', label = 'Bearcat', price = 50000},
		{model = 'riot2', label = 'Water Riot', price = 50000},
		{model = '2020camaro', label = 'CCPI', price = 60000},
		--{model = 'ranger19', label = '19 Ranger', price = 65000},
		--{model = 'notacopcar', label = 'LM SPU', price = 10000000},
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'polcharger2', label = '18 Charger', price = 30000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'polss', label = 'Chevy SS', price = 30000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	}
}

Config.SecuroServAuthorizedVehicles = {
	soldier = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	securo_lt = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	underboss = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	manager = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	truck_driver = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	security_officer = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	senior_security_officer = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	supervisor = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	},

	securo_boss = {
		{model = 'gruppe1', label = 'CVPI', price = 5000},
		{model = 'gruppe2', label = 'Charger', price = 5000},
		{model = 'gruppe3', label = 'FPIU', price = 5000},
		{model = 'stockade', label = 'Bank Truck', price = 5000}
	}
}

Config.UsmarshalAuthorizedVehicles = {
	recruit = {
		{model = 'scorcher', label = 'Bicycle', price = 10}
	},

	deputy1 = {
		{model = 'stopcvpi', label = 'CVPI', price = 5000},
		{model = 'stoptaurus', label = 'Taurus', price = 5000},
		{model = 'stoptahoe', label = 'Tahoe', price = 5000},
		{model = 'stopcharger2', label = 'Unmarked 18 Charger', price = 5000},
		{model = 'stopcharger', label = 'Unmarked 14 Charger', price = 5000},
		{model = 'stopbike', label = 'BMW Bike', price = 5000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	deputy2 = {
		{model = 'stopcvpi', label = 'CVPI', price = 5000},
		{model = 'stoptaurus', label = 'Taurus', price = 5000},
		{model = 'stoptahoe', label = 'Tahoe', price = 5000},
		{model = 'stopcharger2', label = 'Charger', price = 5000},
		{model = 'stopcharger', label = 'Unmarked 14 Charger', price = 5000},
		{model = 'stopbike', label = 'BMW Bike', price = 5000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	supervisor = {
		{model = 'stopcvpi', label = 'CVPI', price = 5000},
		{model = 'stoptaurus', label = 'Taurus', price = 5000},
		{model = 'stoptahoe', label = 'Tahoe', price = 5000},
		{model = 'stopcharger2', label = 'Charger', price = 5000},
		{model = 'stopcharger', label = 'Unmarked 14 Charger', price = 5000},
		{model = 'stopbike', label = 'BMW Bike', price = 5000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	cos = {
		{model = 'stopcvpi', label = 'CVPI', price = 5000},
		{model = 'stoptaurus', label = 'Taurus', price = 5000},
		{model = 'stoptahoe', label = 'Tahoe', price = 5000},
		{model = 'stopcharger2', label = 'Charger', price = 5000},
		{model = 'stopcharger', label = 'Unmarked 14 Charger', price = 5000},
		{model = 'stopbike', label = 'BMW Bike', price = 5000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	},

	us_director = {
		{model = 'stopcvpi', label = 'CVPI', price = 5000},
		{model = 'stoptaurus', label = 'Taurus', price = 5000},
		{model = 'stopcharger2', label = 'Charger', price = 5000},
		{model = 'stopcharger', label = 'Unmarked 14 Charger', price = 5000},
		{model = 'stopbike', label = 'BMW Bike', price = 5000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
	}
}

Config.dodAuthorizedVehicles = {

	ensign = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	petty3rd = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMWV', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	petty2nd = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	petty1st = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	pettychief = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	lt = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	twolt = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	onelt = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	ltcommander = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	commander = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	capt = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'brad', label = 'M2A2 Bradley', price = 20000},
		{model = 'abrams', label = 'M1A2 Abrams', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	major = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'brad', label = 'M2A2 Bradley', price = 20000},
		{model = 'abrams', label = 'M1A2 Abrams', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	ltcol = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'brad', label = 'M2A2 Bradley', price = 20000},
		{model = 'abrams', label = 'M1A2 Abrams', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},

	col = {
		{model = 'cgtahoe', label = 'Tahoe', price = 20000},
		{model = 'bspec', label = 'Base Spec HMMV', price = 20000},
		{model = 'hmvs', label = 'HMMV Spec Ops', price = 20000},
		{model = 'unarmed1', label = 'M1114 Unarmed', price = 20000},
		{model = 'uparmor2', label = 'M1114 Armed W', price = 20000},
		{model = 'mrap', label = 'MRAP', price = 20000},
		{model = 'brad', label = 'M2A2 Bradley', price = 20000},
		{model = 'abrams', label = 'M1A2 Abrams', price = 20000},
		{model = 'barracks', label = 'Barracks', price = 20000}
	},
}

Config.FibAuthorizedVehicles = {
	
	cadet = {
		{model = 'scorcher', label = 'Bicycle', price = 10}
	},

	agent = {
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'hellcatblue', label = 'Hellcat All Blue (Undercover Ops Only)', price = 55000},
		{model = 'hellcatall', label = 'Hellcat Red and Blue (Undercover Ops Only)', price = 55000},
	},

	asac = {
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stopcharger2', label = 'UM Charger 2', price = 35000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'hellcatblue', label = 'Hellcat All Blue (Undercover Ops Only)', price = 55000},
		{model = 'hellcatall', label = 'Hellcat Red and Blue (Undercover Ops Only)', price = 55000},
	},

	sac = {
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stopcharger2', label = 'UM Charger 2', price = 35000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'stopjeep', label = 'UM Jeep', price = 100000},
		{model = 'hellcatblue', label = 'Hellcat All Blue (Undercover Ops Only)', price = 55000},
		{model = 'hellcatall', label = 'Hellcat Red and Blue (Undercover Ops Only)', price = 55000},
	},

	deputy_director = {
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stopcharger2', label = 'UM Charger 2', price = 35000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'hellcatblue', label = 'Hellcat All Blue (Undercover Ops Only)', price = 55000},
		{model = 'hellcatall', label = 'Hellcat Red and Blue (Undercover Ops Only)', price = 55000},
	},

	director = {
		{model = 'stopcvpi', label = 'UM CVPI', price = 10000},
		{model = 'stopcharger', label = 'UM Charger', price = 35000},
		{model = 'stopcharger2', label = 'UM Charger 2', price = 35000},
		{model = 'stoptaurus', label = 'UM TAURUS', price = 10000},
		{model = 'polmustang', label = 'FMPI', price = 60000},
		{model = 'stopbike', label = 'UM BMW Bike', price = 50000},
		{model = 'bf400pol', label = 'Dirtbike', price = 10000},
		{model = 'polfpiu2', label = 'SL Marked FPIU', price = 20000},
		{model = 'stopimpala', label = 'UM Impala', price = 10000},
		{model = 'stopjeep', label = 'UM Jeep', price = 100000},
		{model = 'VettePD', label = 'PD Corvette', price = 100000},
		{model = 'polf350d', label = 'Police ESU (Tac Ops)', price = 75000},
		{model = 'stoptahoe', label = 'UM TAHOE', price = 25000},
		{model = 'silv', label = 'Silverado', price = 55000},
		{model = 'hellcatblue', label = 'Hellcat All Blue (Undercover Ops Only)', price = 55000},
		{model = 'hellcatall', label = 'Hellcat Red and Blue (Undercover Ops Only)', price = 55000},
	}
}

Config.DojAuthorizedVehicles = {
	staffer = {
		{model = 'stopcharger', label = 'Charger', price = 5000},
		{model = 'fbi2', label = 'Escalade', price = 25000}
	},

	clerk = {
		{model = 'stopcharger', label = 'Charger', price = 5000},
		{model = 'fbi2', label = 'Escalade', price = 25000}
	},

	ada = {
		{model = 'stopcharger', label = 'Charger', price = 5000},
		{model = 'fbi2', label = 'Escalade', price = 25000}
	},

	da = {
		{model = 'stopcharger', label = 'Charger', price = 5000},
		{model = 'fbi2', label = 'Escalade', price = 25000}
	},

	judge = {
		{model = 'stopcharger', label = 'Charger', price = 5000},
		{model = 'fbi2', label = 'Escalade', price = 25000}
	},

	chiefjustice = {
		{model = 'stopcharger', label = 'Charger', price = 5000},
		{model = 'fbi2', label = 'Escalade', price = 25000}
	}
}