local Vehicles = {
	{label = 'Blade', spawnName = 'blade'},
	{label = 'Buccaneer', spawnName = 'buccaneer'},
	{label = 'Buccaneer Rider', spawnName = 'buccaneer2'},
	{label = 'Chino', spawnName = 'chino'},
	{label = 'Chino Luxe', spawnName = 'chino2'},
	{label = 'Coquette BlackFin', spawnName = 'coquette3'},
	{label = 'Dominator', spawnName = 'dominator'},
	{label = 'Dukes', spawnName = 'dukes'},
	{label = 'Gauntlet', spawnName = 'gauntlet'},
	{label = 'Hotknife', spawnName = 'hotknife'},
	{label = 'Faction', spawnName = 'faction'},
	{label = 'Faction Rider', spawnName = 'faction2'},
	{label = 'Faction XL', spawnName = 'faction3'},
	{label = 'Nightshade', spawnName = 'nightshade'},
	{label = 'Phoenix', spawnName = 'phoenix'},
	{label = 'Picador', spawnName = 'picador'},
	{label = 'Sabre Turbo', spawnName = 'sabregt'},
	{label = 'Sabre GT', spawnName = 'sabregt2'},
	{label = 'Slam Van', spawnName = 'slamvan3'},
	{label = 'Tampa', spawnName = 'tampa'},
	{label = 'Virgo', spawnName = 'virgo'},
	{label = 'Vigero', spawnName = 'vigero'},
	{label = 'Voodoo', spawnName = 'voodoo'},
	{label = 'Blista', spawnName = 'blista'},
	{label = 'Brioso R/A', spawnName = 'brioso'},
	{label = 'Issi', spawnName = 'issi2'},
	{label = 'Panto', spawnName = 'panto'},
	{label = 'Prairie', spawnName = 'prairie'},
	{label = 'Bison', spawnName = 'bison'},
	{label = 'Bobcat XL', spawnName = 'bobcatxl'},
	{label = 'Burrito', spawnName = 'burrito3'},
	{label = 'Burrito', spawnName = 'gburrito2'},
	{label = 'Camper', spawnName = 'camper'},
	{label = 'Gang Burrito', spawnName = 'gburrito'},
	{label = 'Journey', spawnName = 'journey'},
	{label = 'Minivan', spawnName = 'minivan'},
	{label = 'Moonbeam', spawnName = 'moonbeam'},
	{label = 'Moonbeam Rider', spawnName = 'moonbeam2'},
	{label = 'Paradise', spawnName = 'paradise'},
	{label = 'Rumpo', spawnName = 'rumpo'},
	{label = 'Rumpo Trail', spawnName = 'rumpo3'},
	{label = 'Surfer', spawnName = 'surfer'},
	{label = 'Youga', spawnName = 'youga'},
	{label = 'Youga Luxuary', spawnName = 'youga2'},
	{label = 'Asea', spawnName = 'asea'},
	{label = 'Cognoscenti', spawnName = 'cognoscenti'},
	{label = 'Emperor', spawnName = 'emperor'},
	{label = 'Fugitive', spawnName = 'fugitive'},
	{label = 'Glendale', spawnName = 'glendale'},
	{label = 'Intruder', spawnName = 'intruder'},
	{label = 'Premier', spawnName = 'premier'},
	{label = 'Regina', spawnName = 'regina'},
	{label = 'Schafter', spawnName = 'schafter2'},
	{label = 'Stretch', spawnName = 'stretch'},
	{label = 'Tailgater', spawnName = 'tailgater'},
	{label = 'Warrener', spawnName = 'warrener'},
	{label = 'Washington', spawnName = 'washington'},
	{label = 'Baller', spawnName = 'baller2'},
	{label = 'Baller Sport', spawnName = 'baller3'},
	{label = 'Cavalcade', spawnName = 'cavalcade2'},
	{label = 'Contender', spawnName = 'contender'},
	{label = 'Dubsta', spawnName = 'dubsta'},
	{label = 'Dubsta Luxuary', spawnName = 'dubsta2'},
	{label = 'Fhantom', spawnName = 'fq2'},
	{label = 'Grabger', spawnName = 'granger'},
	{label = 'Gresley', spawnName = 'gresley'},
	{label = 'Huntley S', spawnName = 'huntley'},
	{label = 'Landstalker', spawnName = 'landstalker'},
	{label = 'Mesa', spawnName = 'mesa'},
	{label = 'Mesa Trail', spawnName = 'mesa3'},
	{label = 'Patriot', spawnName = 'patriot'},
	{label = 'Radius', spawnName = 'radi'},
	{label = 'Rocoto', spawnName = 'rocoto'},
	{label = 'Seminole', spawnName = 'seminole'},
	{label = 'XLS', spawnName = 'xls'},
	{label = 'Btype', spawnName = 'btype'},
	{label = 'Btype Luxe', spawnName = 'btype3'},
	{label = 'Btype Hotroad', spawnName = 'btype2'},
	{label = 'Casco', spawnName = 'casco'},
	{label = 'Coquette Classic', spawnName = 'coquette2'},
	{label = 'Manana', spawnName = 'manana'},
	{label = 'Monroe', spawnName = 'monroe'},
	{label = 'Pigalle', spawnName = 'pigalle'},
	{label = 'Stinger', spawnName = 'stinger'},
	{label = 'Stinger GT', spawnName = 'stingergt'},
	{label = 'Stirling GT', spawnName = 'feltzer3'},
	{label = 'S3', spawnName = '2015s3'},
	{label = 'Bifta', spawnName = 'bifta'},
	{label = 'Bf Injection', spawnName = 'bfinjection'},
	{label = 'Blazer Sport', spawnName = 'blazer4'},
	{label = 'Brawler', spawnName = 'brawler'},
	{label = 'Bubsta 6x6', spawnName = 'dubsta3'},
	{label = 'Dune Buggy', spawnName = 'dune'},
	{label = 'Guardian', spawnName = 'guardian'},
	{label = 'Rebel', spawnName = 'rebel2'},
	{label = 'Sandking', spawnName = 'sandking'},
	{label = 'FC', spawnName = 'fc09'},
	{label = 'Trophy Truck', spawnName = 'trophytruck'},
	{label = 'Trophy Truck Limited', spawnName = 'trophytruck2'},
	{label = 'Cognoscenti Cabrio', spawnName = 'cogcabrio'},
	{label = 'Exemplar', spawnName = 'exemplar'},
	{label = 'F620', spawnName = 'f620'},
	{label = 'Felon', spawnName = 'felon'},
	{label = 'Felon GT', spawnName = 'felon2'},
	{label = 'Jackal', spawnName = 'jackal'},
	{label = 'Oracle XS', spawnName = 'oracle2'},
	{label = 'Sentinel', spawnName = 'sentinel'},
	{label = 'Sentinel XS', spawnName = 'sentinel2'},
	{label = 'Windsor', spawnName = 'windsor'},
	{label = 'Windsor Drop', spawnName = 'windsor2'},
	{label = 'Zion', spawnName = 'zion'},
	{label = 'Zion Cabrio', spawnName = 'zion2'},
	{label = '9F', spawnName = 'ninef'},
	{label = '9F Cabrio', spawnName = 'ninef2'},
	{label = 'Alpha', spawnName = 'alpha'},
	{label = 'Banshee', spawnName = 'banshee'},
	{label = 'Bestia GTS', spawnName = 'bestiagts'},
	{label = 'Buffalo', spawnName = 'buffalo'},
	{label = 'Buffalo S', spawnName = 'buffalo2'},
	{label = 'Carbonizzare', spawnName = 'carbonizzare'},
	{label = 'Comet', spawnName = 'comet2'},
	{label = 'Coquette', spawnName = 'coquette'},
	{label = 'Drift Tampa', spawnName = 'tampa2'},
	{label = 'Elegy', spawnName = 'elegy2'},
	{label = 'Feltzer', spawnName = 'feltzer2'},
	{label = 'Furore GT', spawnName = 'furoregt'},
	{label = 'Fusilade', spawnName = 'fusilade'},
	{label = 'Jester', spawnName = 'jester'},
	{label = 'Jester(Racecar)', spawnName = 'jester2'},
	{label = 'Khamelion', spawnName = 'khamelion'},
	{label = 'Kuruma', spawnName = 'kuruma'},
	{label = 'Lynx', spawnName = 'lynx'},
	{label = 'Mamba', spawnName = 'mamba'},
	{label = 'Massacro', spawnName = 'massacro'},
	{label = 'Massacro(Racecar)', spawnName = 'massacro2'},
	{label = 'Omnis', spawnName = 'omnis'},
	{label = 'Penumbra', spawnName = 'penumbra'},
	{label = 'Rapid GT', spawnName = 'rapidgt'},
	{label = 'Rapid GT Convertible', spawnName = 'rapidgt2'},
	{label = 'Schafter V12', spawnName = 'schafter3'},
	{label = 'Seven 70', spawnName = 'seven70'},
	{label = 'Sultan', spawnName = 'sultan'},
	{label = 'Surano', spawnName = 'surano'},
	{label = 'Tropos', spawnName = 'tropos'},
	{label = 'Verlierer', spawnName = 'verlierer2'},
	{label = 'Panamaera Sport', spawnName = 'pturismo'},
	{label = 'Banshee 900R', spawnName = 'banshee2'},
	{label = 'Bullet', spawnName = 'bullet'},
	{label = '718', spawnName = '718'},
	{label = 'ATS-V', spawnName = 'cats'},
	{label = 'Pfister', spawnName = 'pfister811'},
	{label = 'C8', spawnName = 'spyker'},
	{label = 'Reaper', spawnName = 'reaper'},
	{label = 'Sultan RS', spawnName = 'sultanrs'},
	{label = 'T20', spawnName = 't20'},
	{label = 'Modena', spawnName = 'modena'},
	{label = '718 Cayman S', spawnName = '718caymans'},
	{label = 'Vacca', spawnName = 'vacca'},
	{label = 'Voltic', spawnName = 'voltic'},
	{label = 'GTX', spawnName = 'gtx'},
	{label = 'Akuma', spawnName = 'AKUMA'},
	{label = 'Avarus', spawnName = 'avarus'},
	{label = 'Bagger', spawnName = 'bagger'},
	{label = 'Bati 801', spawnName = 'bati'},
	{label = 'Bati 801RR', spawnName = 'bati2'},
	{label = 'BF400', spawnName = 'bf400'},
	{label = 'BMX (velo)', spawnName = 'bmx'},
	{label = 'Carbon RS', spawnName = 'carbonrs'},
	{label = 'Chimera', spawnName = 'chimera'},
	{label = 'Cliffhanger', spawnName = 'cliffhanger'},
	{label = 'Cruiser (velo)', spawnName = 'cruiser'},
	{label = 'Daemon', spawnName = 'daemon'},
	{label = 'Daemon High', spawnName = 'daemon2'},
	{label = 'Defiler', spawnName = 'defiler'},
	{label = 'Double T', spawnName = 'double'},
	{label = 'Enduro', spawnName = 'enduro'},
	{label = 'Esskey', spawnName = 'esskey'},
	{label = 'Faggio', spawnName = 'faggio'},
	{label = 'Vespa', spawnName = 'faggio2'},
	{label = 'Fixter (velo)', spawnName = 'fixter'},
	{label = 'Gargoyle', spawnName = 'gargoyle'},
	{label = 'Hakuchou', spawnName = 'hakuchou'},
	{label = 'Hexer', spawnName = 'hexer'},
	{label = 'Innovation', spawnName = 'innovation'},
	{label = 'Manchez', spawnName = 'manchez'},
	{label = 'Nemesis', spawnName = 'nemesis'},
	{label = 'Nightblade', spawnName = 'nightblade'},
	{label = 'PCJ-600', spawnName = 'pcj'},
	{label = 'Ruffian', spawnName = 'ruffian'},
	{label = 'Sanchez', spawnName = 'sanchez'},
	{label = 'Sanchez Sport', spawnName = 'sanchez2'},
	{label = 'Sanctus', spawnName = 'sanctus'},
	{label = 'Scorcher (velo)', spawnName = 'scorcher'},
	{label = 'Sovereign', spawnName = 'sovereign'},
	{label = 'A45', spawnName = 'a45'},
	{label = 'Thrust', spawnName = 'thrust'},
	{label = 'Tri bike (velo)', spawnName = 'tribike3'},
	{label = 'Vader', spawnName = 'vader'},
	{label = 'Vortex', spawnName = 'vortex'},
	{label = 'Woflsbane', spawnName = 'wolfsbane'},
	{label = 'Zombie', spawnName = 'zombiea'},
	{label = 'Zombie Luxuary', spawnName = 'zombieb'},
	{label = 'Belair', spawnName = 'belair'},
	{label = 'GTO', spawnName = 'gto06'},
	{label = '650S', spawnName = 'mc650'},
	{label = 'RX7 v2', spawnName = 'rx7tunable2'},
	{label = 'M7', spawnName = '750li'},
	{label = 'BRZ', spawnName = 'brz'},
	{label = 'SLK55', spawnName = 'slk55'},
	{label = 'M6', spawnName = 'oldm6'},
	{label = 'P51', spawnName = 'p51'},
	{label = 'Model 3', spawnName = 'tmodel'},
	{label = 'MX5', spawnName = 'mx5rb'},
	{label = 'Civic EK9', spawnName = 'ek9'},
	{label = 'Macan', spawnName = 'macan'},
	{label = 'RX7', spawnName = 'rx7tunable'},
	{label = 'Murcielago', spawnName = 'lambomurcielago'},
	{label = 'C10 SS', spawnName = 'c10ss'},
	{label = 'Lancer EVO10', spawnName = 'evo10'},
	{label = 'Miura', spawnName = 'miura'},
	{label = 'Caprice', spawnName = 'caprice13'},
	{label = 'M600', spawnName = 'm600'},
	{label = 'Regera', spawnName = 'regera'},
	{label = 'Caymen', spawnName = 'pcs18'},
	{label = '812', spawnName = 'ferrari812'},
	{label = 'Hellcat Spec', spawnName = 'hellcatlb'},
	{label = 'Stingray', spawnName = 'stingray66'},
	{label = 'AMG GTS', spawnName = 'amggts'},
	{label = '850R', spawnName = 'v850r'},
	{label = 'Chiron', spawnName = '2017chiron'},
	{label = 'Corvette Z06', spawnName = 'c6z06'},
	{label = 'Fpace', spawnName = 'fpace'},
	{label = 'Camaro ZL1', spawnName = 'cczl'},
	{label = 'Yukon', spawnName = 'gmcyd'},
	{label = '350Z Spec', spawnName = '350z1'},
	{label = 'C63 Coupe', spawnName = 'c63coupe'},
	{label = 'F12', spawnName = 'f12m'},
	{label = 'Lancer', spawnName = 'mlec'},
	{label = 'CX75', spawnName = 'cx75'},
	{label = 'Scirocco', spawnName = 'sciroccos81'},
	{label = 'Supra', spawnName = 'tsup3'},
	{label = 'Miata', spawnName = 'mazlex'},
	{label = 'Hemi Cuda', spawnName = 'hemicuda'},
	{label = 'Charger RT70', spawnName = 'rt70'},

	-- BMW
	{label = 'BMW S1000 RR', spawnName = 'bmws'},
	{label = 'BMW 850', spawnName = 'bmw850'},
	{label = 'BMW S1', spawnName = 'bmws1'},
	{label = 'BMW i8', spawnName = 'i8'},
	{label = 'BMW M4 WB', spawnName = 'f82lw'},
	{label = 'BMW E28', spawnName = 'bmwe28'},
	{label = 'BMW M1 1981', spawnName = 'm1'},
	{label = 'BMW M4 GTS', spawnName = 'rmodm4gts'},
	{label = 'BMW M8 GTE 2020', spawnName = 'm8gte'},
	{label = 'BMW S1000RR Custom V2', spawnName = 'bmwsrn'},
	{label = 'BMW 740i E38', spawnName = '740i'},
	{label = 'Unmarked BMW Bike', spawnName = 'stopbike'},
	{label = 'Marked BMW Bike', spawnName = 'polbike'},
	{label = 'BMW SR Bike', spawnName = 'bmwsr'},
	{label = 'BMW M3 E92', spawnName = 'e92'},
	{label = 'BMW M5 E39 2002', spawnName = 'bmwe39'},
	{label = 'BMW E34', spawnName = 'e34'},
	{label = 'BMW 750', spawnName = 'lumma750'},

	{label = 'Cuda SE', spawnName = 'cuba70'},
	{label = 'GT', spawnName = 'gt2017'},
	{label = 'Bentayga', spawnName = 'bentaygast'},
	{label = '180sx', spawnName = '180sx'},
	{label = 'GTR', spawnName = 'gtrlb'},
	{label = 'Speed 3', spawnName = 'mz3'},
	{label = 'Beatle', spawnName = 'beetle74'},
	{label = 'Eldorado', spawnName = 'e78'},
	{label = 'Pajieluo', spawnName = 'pajieluo'},
	{label = 'Hilux', spawnName = 'hilux99'},
	{label = 'Fiesta', spawnName = 'fiestarbnormal'},
	{label = 'Mustang Rmod', spawnName = 'rmodmustang'},
	{label = 'Odyssey', spawnName = 'ody18'},
	{label = 'CRV', spawnName = 'crv'},
	{label = 'Phantom', spawnName = 'rrphantom'},
	{label = '2000 GT', spawnName = '2000gt'},
	{label = 'Civic', spawnName = 'civic'},
	{label = 'XTS Limo', spawnName = 'limoxts'},
	{label = 'Trail Cat', spawnName = 'trailcat'},
	{label = 'V60R', spawnName = 'v60pols'},
	{label = 'S8', spawnName = 'audis8om'},
	{label = 'M3', spawnName = 'm3f80'},
	{label = 'GNX', spawnName = 'bgnx'},
	{label = 'CTS-V', spawnName = 'ctsv16'},
	{label = 'C10 Step Side', spawnName = 'c10custom'},
	{label = 'Nova', spawnName = 'nova'},
	{label = 'Silverado', spawnName = 'silverado'},
	{label = 'Challenger Rampage', spawnName = 'rampage10'},
	{label = 'Fairlane', spawnName = 'fair500'},
	{label = 'Huracan', spawnName = 'lhuracan'},
	{label = 'Mustang 302', spawnName = '13fmb302'},
	{label = 'Levante', spawnName = 'levante'},
	{label = 'P1 GTR', spawnName = 'p1gtr'},
	{label = '3000gt', spawnName = '3000gt'},
	{label = '370z', spawnName = '370z'},
	{label = 'Silvia S15', spawnName = 's15rb'},
	{label = 'GTO', spawnName = 'gto65'},
	{label = 'Wraith', spawnName = 'wraith'},
	{label = 'Cobra', spawnName = 'cobra'},
	{label = 'Sienna', spawnName = 'sienna'},
	{label = 'Aventador', spawnName = 'ahksv'},
	{label = '458 WB', spawnName = 'pd458wb'},
	{label = 'SLS', spawnName = 'sls'},
	{label = 'Agera', spawnName = 'ageraone'},
	{label = 'Ferarri F40', spawnName = 'f40'},
	{label = 'S63', spawnName = 's63w222'},
	{label = '918c', spawnName = '918'},
	{label = '65 Mustang Boss', spawnName = 'boss302'},
	{label = 'Renegade', spawnName = 'jeepreneg'},
	{label = '92 Prelude', spawnName = '92prelude'},
	{label = '65 Mustang', spawnName = 'mustang65'},
	{label = 'Vulcan', spawnName = 'vulcan'},
	{label = 'DB9', spawnName = 'db905'},
	{label = 'G Wagon', spawnName = 'g65'},
	{label = 'Integra', spawnName = 'dc2'},
	{label = 'DB11', spawnName = 'ad11'},
	{label = 'Vanquish', spawnName = 'ast'},
	{label = 'One-77', spawnName = 'one77'},
	{label = 'RS5', spawnName = 'rs5'},
	{label = 'RS6', spawnName = 'rs6'},
	{label = 'RS7', spawnName = 'rs7'},
	{label = 'M5', spawnName = 'bmci'},
	{label = 'M4', spawnName = 'm4gts'},
	{label = 'Royale', spawnName = 'royale'},
	{label = 'Escalade', spawnName = 'gmt900escalade'},
	{label = 'Tahoe', spawnName = 'tahoe'},
	{label = 'Coronet', spawnName = 'dodge440'},
	{label = 'Viper', spawnName = 'viper'},
	{label = 'Focus RS', spawnName = 'focusrs'},
	{label = 'Raptor', spawnName = 'raptor12'},
	{label = 'Shelby GT 500', spawnName = 'shelbygt500'},
	{label = 'Escort ', spawnName = 'fordeh2'},
	{label = 'S2000', spawnName = 's2k'},
	{label = 'Accord', spawnName = 'cu2'},
	{label = 'Fit', spawnName = 'ge8'},
	{label = 'Civic Type R', spawnName = 'hondacivictr'},
	{label = 'Etype', spawnName = 'etype'},
	{label = 'P7', spawnName = 'p7'},
	{label = 'XFR', spawnName = 'xfr'},
	{label = 'XJ220 ', spawnName = 'xj220'},
	{label = 'Rubicon', spawnName = 'rubi3d'},
	{label = 'LC500', spawnName = 'lc500'},
	{label = 'SQ7', spawnName = 'sq72016'},
	{label = 'Tr22 roadster', spawnName = 'tr22'},
	{label = 'Sterling', spawnName = 'moss'},
	{label = 'M6', spawnName = 'm6f13'},
	{label = 'Silverado Lifted', spawnName = '1500dj'},
	{label = '16 Charger', spawnName = '16charger'},
	{label = 'XJ', spawnName = 'xj'},
	{label = 'Veneno', spawnName = 'rmodveneno'},
	{label = 'Supra 2', spawnName = 'supra2'},
	{label = 'Evo Q', spawnName = 'evoq'},
	{label = 'Lykan', spawnName = 'lykan'},
	{label = 'F350', spawnName = 'f350low'},
	{label = 'T Coupe', spawnName = 'hotrod2'},
	{label = 'T Body', spawnName = 'durty16'},
	{label = 'Bronco', spawnName = 'mudsl'},
	{label = 'Continental GT', spawnName = 'contgt2011'},
	{label = 'Emperor ', spawnName = 'emperor2'},
	{label = 'C63 Sedan', spawnName = 'c63'},
	{label = 'HD SS', spawnName = 'hdss'},
	{label = 'Suzuki GSXR', spawnName = 'gsxr'},
	{label = 'Harley Davidson Hanger', spawnName = 'hdkn'},
	{label = 'Hasquna moto', spawnName = 'hsmxe'},
	{label = 'Kawasaki Ninja H2', spawnName = 'knh22'},
	{label = 'Yamaha R6', spawnName = 'r6'},
	{label = 'KTM 450 ', spawnName = 'sxf450'},
	{label = 'Yamaha YRD 1000', spawnName = 'yrd1'},
	{label = '720s', spawnName = '720s'},
	{label = 'Mustang Cobra', spawnName = 'shitstang'},
	{label = 'EXP', spawnName = 'bexp'},
	{label = 'X6', spawnName = 'x6m'},
	{label = 'E36 Drag', spawnName = 'e36gda'},
	{label = 'Bati Drag', spawnName = 'hakuchou2'},
	{label = 'Roadmaster', spawnName = 'rmaster'},
	{label = 'Super Sport', spawnName = 'ben17'},
	{label = 'MQ', spawnName = 'mqgts'},
	{label = '71 Skyline', spawnName = 'kgc10'},
	{label = 'Corvette C7', spawnName = 'c7'},
	{label = 'Cayman GT4', spawnName = 'cayman'},
	{label = 'Demon', spawnName = 'demon'},
	{label = 'Mustang Drift', spawnName = 'drifter'},
	{label = 'Gran Tour', spawnName = 'granlb'},
	{label = 'Camaro RS', spawnName = 'hs'},
	{label = 'KTMx', spawnName = 'ktmx'},
	{label = 'M3 E46', spawnName = 'm3e46'},
	{label = 'Ram Off Road', spawnName = 'runner'},
	{label = 'Camaro Z28', spawnName = 'z2879'},
	{label = 'Huayra', spawnName = 'bc'},
	{label = 'Dodge Mega Ram', spawnName = 'megaram'},
	{label = 'Audi R8', spawnName = 'ar8lb'},
	{label = '250 GTO', spawnName = 'gto2'},
	{label = 'Super Diamond', spawnName = 'superd'},
	{label = 'Mercedes Sl 300', spawnName = 'mb300sl'},
	{label = 'Mitshubishi Eclipse', spawnName = 'eclipse'},
	{label = 'Mercedes SL63 Coupe', spawnName = 'benzsl63'},
	{label = 'Mercedes S500', spawnName = 'w221s500'},
	{label = 'Toyota Rav 4', spawnName = 'rav4'},
	{label = 'Range Rover', spawnName = 'rr14'},
	{label = 'Tesla Model S', spawnName = 'models'},
	{label = 'Honda S2000', spawnName = 'ap2'},
	{label = 'Fiat Punto', spawnName = 'Punto'},
	{label = 'Chrysler 300', spawnName = 'chry300'},
	{label = 'Chevy Chevelless', spawnName = 'chevelless'},
	{label = 'Audi S8', spawnName = 'audis8om'},
	{label = '1976 Corvette GT', spawnName = 'vette'},
	{label = '84 288 GTO', spawnName = 'f288gto'},
	{label = 'Countach NT', spawnName = 'count6'},
	{label = 'Countach HT', spawnName = 'count52'},
	{label = '69 Fair Lady Z', spawnName = 's30'},
	{label = '76 Ferrari 512 BB', spawnName = 'bb512'},
	{label = '93 McLaren F1', spawnName = 'f1'},
	{label = '64 Porshe 911', spawnName = 'p901'},
	{label = '65 Ford GT 40', spawnName = 'fg4m'},
	{label = 'Centenario', spawnName = 'rmodlp750'},

	-- Nissan
	{label = 'Nissan Titan 2017', spawnName = 'titan17'}, -- TODO one is broken
	{label = 'Nissan Titan 2017', spawnName = 'nissantitan17'}, -- TODO one is broken
	{label = 'Nissan 200SX S13 1998', spawnName = 'ns13'},
	{label = 'Nissan Skyline GTR R34 2001', spawnName = 'skyline2'},
	{label = 'Nissan GTR R35 2017', spawnName = 'gtr'},
	{label = 'Nissan GTR 2016', spawnName = 'r35'},
	{label = 'Nissan GTS R31 1987', spawnName = 'r31'},

	{label = '16 Audi R8', spawnName = 'r8ppi'},
	{label = 'McLaren P1', spawnName = 'p1'},
	{label = '18 NSX', spawnName = 'nc1'},
	{label = 'GMC Sierra', spawnName = 'gmcs'},
	{label = 'AMG GT3', spawnName = 'amggt3'},
	{label = 'F450', spawnName = 'mathis'},
	{label = '70 Dodge Super Bee', spawnName = 'bee'},
	{label = 'Subaru WRX', spawnName = '04subwrx'},
	{label = '12 Eagle Roadster', spawnName = 'eagle'},
	{label = '18 Mustang GT', spawnName = 'mustangbkit'},
	{label = 'Lexus RCF', spawnName = 'rcf'},
	{label = 'Lambo lp670', spawnName = 'lwlp670'},
	{label = 'Crown Victoria', spawnName = 'crownvic'},

	{label = 'kawasaki zx10r', spawnName = 'zx10r'},
	{label = 'mazda', spawnName = 'mazda6'},
	{label = 'Lambo Aventador', spawnName = 'zentorno2'},
	{label = 'Toyota Supra trd', spawnName = 'a80'},
	{label = 'Ferarri 488', spawnName = 'fm488'},
	{label = 'Pagani Huayrar', spawnName = 'huayrar'},
	{label = '15 subaru sti', spawnName = 'sti2'},
	{label = '98 Subaru STI', spawnName = 'sim22'},
	{label = '1960 Corvette C1', spawnName = 'cc1'},
	{label = 'Humvee', spawnName = 'Humvee'},
	{label = 'Willy Jeep', spawnName = 'willysmb'},
	{label = 'Rancher XL Extreme', spawnName = 'rancherxlextreme'},
	{label = 'Honda Civic eg6', spawnName = 'eg6'},
	{label = 'V8 sultan rs', spawnName = 'sultanrsv82'},
	{label = 'Venom GT', spawnName = 'xnsgt'},
	{label = 'Maserato Ghibli', spawnName = 'ghis2'},
	{label = 'McLaren senna', spawnName = 'senna'},
	{label = '92 Dodge Ram', spawnName = '92dodgeram'},
	{label = 'Lifted Raptor', spawnName = 'caracarase'},
	{label = 'OffRoad Charger', spawnName = 'charge4'},
	{label = '18 RHD Type R', spawnName = 'fk8'},
	{label = '80 Silverado-lifted', spawnName = '80silverado'},
	{label = 'Evo IX', spawnName = 'evo92'},
	{label = 'Acura RSX', spawnName = 'trintegra'},
	{label = '05 Ford GT', spawnName = 'fgt'},
	{label = 'Comet Classic', spawnName = 'comet3'},
	{label = '2018 Comet', spawnName = 'comet5'},
	{label = 'Ruston', spawnName = 'ruston'},
	{label = 'Raptor', spawnName = 'raptor'},
	{label = 'Specter Custom', spawnName = 'specter2'},
	{label = 'Seven70', spawnName = 'seven70'},
	{label = 'Z-Type', spawnName = 'ztype'},
	{label = 'Osiris', spawnName = 'osiris'},
	{label = 'FMJ', spawnName = 'fmj'},
	{label = 'Sheava', spawnName = 'sheava'},
	{label = 'Issi Mini Classic', spawnName = 'issi3'},
	{label = 'Vulcar Fagaloa', spawnName = 'fagaloa'},
	{label = 'Vapid Ellie', spawnName = 'ellie'},
	{label = 'Tyrus', spawnName = 'tyrus'},
	{label = 'Flash GT', spawnName = 'flashgt'},
	{label = '2018 Dominator GT', spawnName = 'dominator3'},
	{label = 'Sentinel Classic', spawnName = 'sentinel3'},
	{label = 'Kamacho', spawnName = 'kamacho'},
	{label = 'Cheburek', spawnName = 'cheburek'},
	{label = 'Elegy Classic', spawnName = 'elegy'},
	{label = 'Neon', spawnName = 'neon'},
	{label = 'Penetrator Classic', spawnName = 'penetrator'},
	{label = 'XA-21', spawnName = 'xa21'},
	{label = 'Vapid GB200', spawnName = 'gb200'},
	{label = 'Mercedes e500', spawnName = 'e500'},
	{label = '911 GT2RS', spawnName = 'gt2rs'},
	{label = '17 Rolls-Royce Sweptail', spawnName = 'sweptail'},
	{label = '16 WRX STI', spawnName = '16wrxsti'},
	{label = '12 Lamborghini Aventador Speedster', spawnName = 'avj'},
	{label = 'Taco Truck', spawnName = 'taco'},
	{label = '69 Dodge Charger', spawnName = '69charger'},
	{label = 'Caddy 3', spawnName = 'caddy3'},
	{label = 'GT350 WB', spawnName = 'mustangbkitwb'},
	{label = 'Rapid GT Classic', spawnName = 'rapidgt3'},
	{label = 'Michelli GT', spawnName = 'michelli'},
	{label = 'Retinue', spawnName = 'retinue'},
	{label = '190z', spawnName = 'z190'},
	{label = 'Nero Custom', spawnName = 'nero2'},
	{label = 'Buccaneer Lowrider', spawnName = 'buccaneer2'},
	{label = 'Chino Lowrider', spawnName = 'chino2'},
	{label = 'Faction Lowrider', spawnName = 'faction2'},
	{label = 'Faction Doink', spawnName = 'faction3'},
	{label = 'Minivan Lowrider', spawnName = 'minivan2'},
	{label = 'Moonbeam Lowrider', spawnName = 'moonbeam2'},
	{label = 'Primo Lowrider', spawnName = 'primo2'},
	{label = 'sabre lowrider', spawnName = 'sabregt2'},
	{label = 'SlamVan Lowrider', spawnName = 'slamvan3'},
	{label = 'Virgo Lowrider', spawnName = 'virgo2'},
	{label = 'VooDoo Lowrider', spawnName = 'voodoo'},
	{label = 'Marcin Vehicle ', spawnName = 'firebird'},
	{label = 'Robin', spawnName = 'robin'},
	{label = 'Rusty Rebel ', spawnName = 'rebel'},
	{label = 'Italigtb Custom', spawnName = 'italigtb2'},
	{label = 'Kitt', spawnName = 'kitt'},
	{label = 'Ford F150 XLT', spawnName = 'f15078'},
	{label = 'CLK LM', spawnName = 'clklm'},
	{label = 'Challenger 70', spawnName = 'chall70'},
	{label = 'Audi Gumball', spawnName = 'imsa90'},
	{label = 'Black Widow', spawnName = 'demon2'},
	{label = 'Ice Charger', spawnName = 'chargerf8'},
	{label = 'Subi Gumball', spawnName = 'ssgt'},
	{label = 'Vantage', spawnName = 'vantage'},
	{label = 'Rat Rod', spawnName = 'ford34'},
	{label = 'Trans AM', spawnName = '2018transam'},
	{label = 'Jeep', spawnName = 'jp12'},
	{label = 'Ski-do', spawnName = 'blazer'},
	{label = 'GLS63 AMG 15', spawnName = 'gls63'},
	{label = 'Lambo Diablo 500gtr', spawnName = '500gtrlam'},
	{label = 'Chevy Impala', spawnName = 'impalass'},
	{label = '99 NSX', spawnName = 'na1'},
	{label = 'R34 Skyline GTR', spawnName = 'skyline'},
	{label = 'E92 WB M3', spawnName = 'e92lb'},
	{label = 'La Ferarri', spawnName = 'aperta'},
	{label = 'Toyota Prius', spawnName = 'prius'},
	{label = 'Lost M.C. Burrito', spawnName = 'gburrito'},
	{label = 'JZX100', spawnName = 'mk2100'},
	{label = 'eb110', spawnName = 'eb110'},
	{label = '83 Volvo 242 Turbo', spawnName = 'v242'},
	{label = 'Unmarked Taurus', spawnName = 'stoptaurus'},
	{label = 'Unmarked Silverado', spawnName = 'stopsilverado'},
	{label = 'Unmarked Raptor', spawnName = 'stopraptor'},
	{label = 'Unmarked Ram', spawnName = 'stopram'},
	{label = 'Unmarked Mustang', spawnName = 'stopmustang'},
	{label = 'Unmarked Jeep', spawnName = 'stopjeep'},
	{label = 'Unmarked Impala', spawnName = 'stopimpala'},
	{label = 'Unmarked Crown Vic', spawnName = 'stopcvpi'},
	{label = 'Unmarked 18 Charger', spawnName = 'stopcharger2'},
	{label = 'Unmarked 14 Charger', spawnName = 'stopcharger'},
	{label = 'Unmarked Caprice', spawnName = 'stopcaprice'},
	{label = 'Sheriff Raptor', spawnName = 'sraptor2'},
	{label = 'Marked Taurus', spawnName = 'poltaurus'},
	{label = 'Trooper Chevy SS', spawnName = 'polss'},
	{label = 'Marked Ram', spawnName = 'polram'},
	{label = 'Marked Mustang', spawnName = 'polmustang'},
	{label = 'Marked Impala', spawnName = 'polimpala'},
	{label = 'Marked FPIU (Lightbar)', spawnName = 'polfpiu'},
	{label = 'Marked FPIU (No Lightbar)', spawnName = 'polfpiu2'},
	{label = 'Marked CVPI', spawnName = 'polcvpi'},
	{label = 'Marked 14 Charger', spawnName = 'polcharger'},
	{label = 'Marked 18 Charger', spawnName = 'polcharger2'},
	{label = 'Ghost Charger', spawnName = 'interceptor'},
	{label = 'Command Tahoe', spawnName = 'firetahoe'},
	{label = 'Ford Territory', spawnName = 'fibfpiu'},
	{label = 'F450 Ambulance', spawnName = 'duty'},
	{label = 'Coast Guard Tahoe', spawnName = 'cgtahoe'},
	{label = 'LSPD Caprice', spawnName = 'capriceleo'},
	{label = 'Air One', spawnName = 'as350'},
	{label = 'Medic Heli', spawnName = 'emsheli'},
	{label = 'Mathis Is Watching', spawnName = 'notacopcar'},
	{label = 'Bradley Is Watching', spawnName = 'notacopcar2'},
	{label = 'Unmarked Bati Bike', spawnName = 'polbati'},
	{label = 'Emergency Responce', spawnName = 'pdbrick'},
	{label = 'Transport Van', spawnName = 'policet'},
	{label = 'Bearcat', spawnName = 'bcsoriot'},
	{label = 'CCPI', spawnName = '2020camaro'},
	{label = '19 Raptor', spawnName = 'ranger19'},
	{label = '18 Silverado', spawnName = '18silverado'},
	{label = 'Silverado', spawnName = 'silv'},
	{label = 'Water Riot', spawnName = 'riot2'},
	{label = 'Emergency Responce SRT', spawnName = 'swatbrickade'},
	{label = 'K5 Blazer', spawnName = 'k5'},
	{label = 'Bugatti Veyron Supersport', spawnName = 'supersport'},
	{label = '1966 Ford Fastback', spawnName = '66fastback'},
	{label = '2015 Ferrari 488 GTB', spawnName = '488gtb'},
	{label = '2016 Subaru WRX STI', spawnName = '2016wrx'},
	{label = 'Bugatti Divo', spawnName = 'divo'},
	{label = '2016 Subaru WRX STI', spawnName = '2016wrx'},
	{label = 'Bugatti Veyron Sang Noir', spawnName = 'snoir'},
	{label = 'Beck', spawnName = 'beck'},
	{label = '2017 Honda CBR1000', spawnName = 'hcbr17'},
	{label = 'Motoc, Sell with City', spawnName = 'motoc'},
	{label = '2003 Dodge Lifted Ram', spawnName = '03ramk'},
	{label = '1985 Honda City', spawnName = 'city85'},
	{label = 'Dodge Challenger Raid', spawnName = 'raid'},
	{label = '2018 Toyota Camry Tuned', spawnName = 'cam8tun'},
	{label = '1995 GMC 2500', spawnName = '952500'},
	{label = 'Dodge Neon', spawnName = 'srt4'},
	{label = 'Dodge 3500 Flatbed', spawnName = '3500flatbed'},
	{label = '2017 Ford Raptor', spawnName = 'raptor2017'},
	{label = 'Chrysler 300C SRT8', spawnName = '300srt8'},
	{label = 'Lamborghini Urus', spawnName = 'urus2018'},
	{label = 'Lamborghini Terzo Millennio 2018', spawnName = 'lamtmc'},
	{label = '2016 Aston Martin V12 Vantage S', spawnName = 'astv12s'},
	{label = '2019 Ford Mustang', spawnName = 'mustang19'},
	{label = 'Alfa Romeo Giulia Quadrifoglio', spawnName = 'aqv'},
	{label = 'Porsche 911 R', spawnName = '911r'},
	{label = 'Toyota MR2 MKI', spawnName = 'mr2'},
	{label = 'Jeep TrackHaw Grand Cherokee', spawnName = 'trhawk'},
	{label = 'Audi RS6', spawnName = 'audirs6tk'},
	{label = 'Audi TT RS', spawnName = 'tts'},
	{label = '2008 Toyota Camry', spawnName = 'cam08'},
	{label = 'Mazda Twerkstallion', spawnName = 'rx7twerk'},
	{label = 'Dodge Ram Runner', spawnName = 'ramrunner'},
	{label = 'Mercedes CLA 45 Shooting Brake', spawnName = 'cla45sb'},
	{label = 'Mitsubishi Lancer Evo 4', spawnName = 'cp9a'},
	{label = '1959 Eldorado', spawnName = 'eldorado59'},
	{label = 'Police Unmarked Chevy Tahoe', spawnName = 'stoptahoe'},
	{label = 'Police Unmarked Ford Explorer', spawnName = 'stopfpiu'},
	{label = '05\' Carrera GT', spawnName = 'cgt'},
	{label = 'Surfer Sport', spawnName = 'surferd'},
	{label = 'NA Miata', spawnName = 'na6'},
	{label = 'Silver Shadow', spawnName = 'silver67'},
	{label = 'E60 M5', spawnName = 'bme6tun'},
	{label = '190E', spawnName = 'benz190e'},
	{label = 'Deadringer', spawnName = 'deadringer'},
	{label = 'Surfer Dual Cab', spawnName = 'surfdcab'},
	{label = 'G63', spawnName = 'g63'},
	{label = 'Primo ARD', spawnName = 'primoard'},
	{label = 'Actros Motorhome', spawnName = 'mbhome'},
	{label = 'M5 F90 Widebody', spawnName = 'm5f90'},
	{label = 'Yamaha R1', spawnName = 'r1'},
	{label = 'Fxxk2', spawnName = 'fxxk2'},
	{label = '1986 Silverado', spawnName = 'silv86'},
	{label = '720 S', spawnName = 'mc720s'},
	{label = 'Saleen Mustang', spawnName = 'saleen'},
	{label = 'Huracan Peformante', spawnName = 'lhuracan'},
	{label = 'Hoonicorn V3', spawnName = 'keenblock'},
	{label = '2017 AMG GTR', spawnName = 'amggtr'},
	{label = '2018 StarTech', spawnName = 'rrst'},
	{label = '2016 R8 V10', spawnName = 'r8v10'},
	{label = '2003 Trailblazer', spawnName = 'trailblazer'},
	{label = '2015 Golf RB', spawnName = 'mk7pandem'},
	{label = 'Porsche 911 993 RWB', spawnName = '993rwb'},
	{label = 'Ford Dually', spawnName = '18f350d'},
	{label = 'E36 RB', spawnName = 'e36rb'},
	{label = 'Yosemite 6STR', spawnName = 'yosemite6str'},
	{label = '1983 Dodge Diplomat', spawnName = 'diplomat83'},
	{label = 'Ellie Drift', spawnName = 'ellie6str'},
	{label = 'Karin Ensenada', spawnName = 'ensenada'},
	{label = '1959 Impala', spawnName = 'impala59c'},
	{label = '1970 Challenger 440', spawnName = 'rt440'},
	{label = '1985 Ford LTD LX', spawnName = 'ltd85'},
	{label = '2015 918 Spyder', spawnName = 'p918spyder'},
	{label = 'Hilux AT38', spawnName = 'hiluxarctic'},
	{label = 'Ford F100', spawnName = 'f100'},
	{label = 'Dodge Lifted Ram 2019', spawnName = '19ramoffroad'},
	{label = '1982 E150', spawnName = 'e15082'},
	{label = 'Surfer Camper', spawnName = 'surfcamper'},
	{label = '2015 S60 Polestar', spawnName = 's60pole'},
	{label = '1994 Impala SS', spawnName = 'impala'},
	{label = 'Excursion Lifted', spawnName = '00excursion'},
	{label = '2012 Donk 300C', spawnName = 'donk300'},
	{label = 'ZR380 Sport', spawnName = 'zr3806str'},
	{label = 'Fleetwood Jamboree', spawnName = '17jamb'},
	{label = '1962 250 GTO', spawnName = 'f250gto64'},
	{label = 'Stelvio Quadrifoglio', spawnName = 'stelvio'},
	{label = 'Surfer Single Cab', spawnName = 'surfcab'},
	{label = 'Caracara Sport', spawnName = 'cara'},
	{label = 'Land Rover Series 3', spawnName = 'landseries3'},
	{label = 'Nexus', spawnName = 'nexus'},
	{label = 'F&F Civic', spawnName = 'fnfcivic'},
	{label = 'Track Hawk', spawnName = 'trhawk'},
	{label = 'Yamaha R25', spawnName = 'r25'},
	{label = 'Lexus LX570', spawnName = 'wald2018'},
	{label = 'Sierra Denali', spawnName = 'denali16'},
	{label = '1965 C10', spawnName = '65c10'},
	{label = '2016 M2', spawnName = 'm2'},
	{label = 'C63 Coupe', spawnName = 'c63s'},
	{label = '2012 E63 AMG', spawnName = 'e63amg'},
	{label = 'Annis Hizoku', spawnName = 'hizoku'},
	{label = 'Hayabusa', spawnName = 'shdrag'},
	{label = 'Hudson Hornet', spawnName = 'hudhorc'},
	{label = 'Aventador LP750 Liberty Walk', spawnName = 'lb750sv'},
	{label = 'Mercedes 6x6', spawnName = 'm6x6'},
	{label = 'Dodge Ram 2500 Lifted', spawnName = 'ram2500lifted'},
	{label = 'Mercedes AMG SLS', spawnName = 'slsamg'},
	{label = 'Lamborghini Aventador', spawnName = 'aventador'},
	{label = 'Jeep JP12 V2', spawnName = 'jp12v2'},
	{label = '2006 Dodge Charger', spawnName = '06charger'},
	{label = 'Lamborghini Performante', spawnName = 'lhuracan'},
	{label = 'Corvette ZR1', spawnName = 'corvettezr1'},
	{label = 'Ford Mustang GT', spawnName = 'msgt'},
	{label = 'Camaro Exorcist', spawnName = 'exor'},
	{label = 'Kia Stinger GT', spawnName = 'kiagt'},
	{label = 'Aston Martin DB11', spawnName = 'db11'},
	{label = 'Mercedes GT63 RMOD', spawnName = 'rmodgt63'},
	{label = 'Bison V2', spawnName = 'bison4'},
	{label = 'Crabby Patty', spawnName = 'patty'},
	{label = 'Ford F150', spawnName = 'f150'},
	{label = 'Jeep Trackhawk', spawnName = 'trackhawk'},
	{label = 'Audi R8 LMS', spawnName = 'r8lms'},
	{label = 'Jeep Trailblazer', spawnName = 'trailblazer'},
	{label = '1983 Dodge Diplomat', spawnName = 'diplomat83'},
	{label = 'Chevrolet Cruze', spawnName = 'cruze'},
	{label = 'Cadillac CTS-V', spawnName = 'ctsv16'},
	{label = '2004 911 GT3', spawnName = 'p996gt3'},
	{label = '2016 Infinity Q60 S', spawnName = 'infq60'},
	{label = '2018 AMG GTS', spawnName = 'amggt18'},
	{label = 'BF Benito', spawnName = 'bfbenito'},
	{label = '2020 R1', spawnName = '20r1'},
	{label = '1993 Ford Mustang SVT', spawnName = '93mustang'},
	{label = '2017 Dodge Ram 2500', spawnName = 'ram2500'},
	{label = '2006 Mercedes S600', spawnName = 's600w220'},
	{label = 'Ford Mustang GT', spawnName = 'mstgt'},
	{label = 'Ford F350 Dually', spawnName = '00f350dually'},
	{label = 'Porsche RUF 911 GT3RS', spawnName = 'wbgt3'},
	{label = 'RMOD Supra', spawnName = 'rmodsupra'},
	{label = 'Ford F100', spawnName = 'f100'},
	{label = 'McLaren 675LT', spawnName = '675ltsp'},
	{label = 'McLaren P1 2014', spawnName = 'mcp1'},
	{label = 'Lykan Fenyr Supersport', spawnName = 'wmfenyr'},
	{label = 'Yosemite Drag Truck', spawnName = 'yosemitedrag'},
	{label = 'Bugatti Veyron 16.4 2009', spawnName = 'bug09'},
	{label = 'Ford Fastback Hoonicorn 1965', spawnName = 'keenblock'},
	{label = 'Ford Taurus Gruppe6 2016', spawnName = 'gruppe1'},
	{label = 'Dodge Charger Gruppe6 2018', spawnName = 'gruppe2'},
	{label = 'Ford Explorer Gruppe6 2016', spawnName = 'gruppe3'},
	{label = 'Chevy Monte Carlo 1970', spawnName = 'montecarlo'},
	{label = '1990 911', spawnName = 'p964lbau'},
	{label = 'Ferrari F430 Scuderia 2005', spawnName = 'f430s'},
	{label = 'BMW M1 Racecar 1977', spawnName = 'm1procar'},
	{label = 'Lamborghini Gallardo Superleggera 2013', spawnName = 'gallardosuperlb'},
	{label = 'Nagasaki BF400 Police', spawnName = 'bf400pol'},
	{label = 'Chevy Tahoe Police LightBar 2016', spawnName = 'poltahoe'},
	{label = 'Chevy Tahoe Police No LightBar 2016', spawnName = 'poltahoe2'},
	{label = 'Pagani Zonda Cinque 2017', spawnName = 'zondacinque'},
	{label = 'Koenigsegg CCX', spawnName = 'ccx'},
	{label = 'Shelby Cobra 1966', spawnName = '427cobra'},
	{label = 'Lamborghini Huracan WideBody 2018', spawnName = '610lb'},
	{label = 'BMW M760i 2017', spawnName = '17m760i'},
	{label = 'Porsche 718 Boxster 2019', spawnName = '718b'},
	{label = 'Nissan 180sx RB 1998', spawnName = '180sxrb'},
	{label = 'Ford Mustang 2015', spawnName = 'mgt'},
	{label = 'Ford F350 Super Duty Lifted 2016', spawnName = 'f350'},
	{label = 'Armored Truck', spawnName = 'insurgentce'},
	{label = 'Armored Truck', spawnName = 'armordillo'},
	{label = 'Lamborghini Aventador SVJ 2019', spawnName = 'svj'},
	{label = 'Lexus GS350 2013', spawnName = 'gs350'},
	{label = 'Porsche 911 GT2 RS 2018', spawnName = 'p911gt2rs'},
	{label = 'Nissan Skyline GTR R32 1989', spawnName = 'r32'},
	{label = 'Porsche Turbo S Moshammer 2015', spawnName = '63lb'},
	{label = 'Koenigsegg Agera RS 2018', spawnName = 'agerars'}
}

Citizen.CreateThread(function()
	for index,vehicle in ipairs(Vehicles) do
		local modelHash = GetHashKey(vehicle.spawnName)

		if IsModelInCdimage(modelHash) then
			AddTextEntryByHash(modelHash, vehicle.label)
		else
			print(('adrp_labels: ignoring invalid vehicle "%s"'):format(vehicle.spawnName))
		end
	end

	-- Pause menu
	AddTextEntry('FE_THDR_GTAO', ('~r~American~s~ Dream ~b~Roleplay~s~ | americandreamrp.com | discord.io/ADRP | ID: ~y~%s~s~'):format(GetPlayerServerId(PlayerId())))
end)
